"""Versioned thresholds for deterministic visual interpretation policy V1."""

MELD_MIN_TILE_CONFIDENCE = 0.70
SIDEWAYS_MIN_DEGREES = 60.0
SIDEWAYS_MAX_DEGREES = 120.0
WINNING_TILE_MIN_GAP_RATIO = 0.45
WINNING_TILE_MIN_CONFIDENCE = 0.70
MAX_VISUAL_CONFIDENCE = 0.95
MAX_UNCONFIRMED_CONFIDENCE = 0.69
